version: "3.9"

services:
  app:
    build: .
    container_name: notification_app
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
      - kafka
    networks:
      - notification-network

  nginx:
    image: nginx:alpine
    container_name: notification_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - notification-network

  mysql:
    image: mysql:8.0
    container_name: notification_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notification-network

  redis:
    image: redis:alpine
    container_name: notification_redis
    networks:
      - notification-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile.queue
    container_name: notification_queue
    restart: always
    depends_on:
      - redis
      - mysql
    networks:
      - notification-network

  kafka:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: notification_kafka
    networks:
      - notification-network

volumes:
  mysql_data:

networks:
  notification-network:
    driver: bridge